### ISSUE TITLE
what is this line doing?

### ISSUE THREAD

**Issue by goswinr** [theimowski/safe-demo-fsharp-exchange-18#1]
Amazing talk Tomasz! what is this line doing exactly ?
`OnChange (fun e -> action !!e.target?value)`
its always difficult too google for operators.

**Comment by theimowski** [comment]
Thanks :)
The line uses "dynamic" capabilities of F# to emit corresponding JavaScript, without static typing - the type of `e` argument does not know that the object (event) has `target` property. As a result the emitted javascript is simply `e.target.value`
