### ISSUE TITLE
Not a really issue

### ISSUE THREAD

**Issue by srlopez** [theimowski/safe-demo-fsharp-exchange-18#2]
I am trying to reproduce your excellent presentation of SAFE in the eXchange of 2018.
I'm working on a container (https://cloud.docker.com/repository/docker/srlopez/safe/)
My starting point is:
dotnet new SAFE --layout fulma-landing --communication remoting
As you can see i planning do Remoting with Saturn.

But I find, at the very beginning, that when entering the image in `Client.fs`, this code:
`
  Image.image [Image.Is128x128] [img [Src imgSrc]]
`
works perfectly, but simply add a Style
`
  Image.image [Image.Is128x128] [img [Src imgSrc Style [Border "1px solid"]]]
`
Give the following error
```
ERROR in ./src/Client/Client.fs
Module Error (from ./node_modules/fable-loader/index.js):
/app/src/Client/Client.fs(178,38): (178,48) error FSHARP: This value is not a function and cannot be applied.
 @ ./src/Client/Client.fsproj 1:0-28 1:0-28
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./src/Client/Client.fsproj
```
I have really searched everywhere, but I can not find which is the `paket add ????` or module to add to the source.

After this I would like to do Remoting with Saturn insted of Suave. What is your opinion?
Thanks in advance.

PLESE CLOSE THEN ISSUE
Solved at https://github.com/fable-compiler/fable-react/issues/156

**Comment by theimowski** [comment]
Happy to hear the issue has been solved.
Yes, Remoting should work fine with Saturn - it's a good way to iterate quickly on your API
